package net.codeinreal.amirahmadadibi.applications.archsample.model

import androidx.databinding.BaseObservable
import androidx.databinding.Bindable
import net.codeinreal.amirahmadadibi.applications.archsample.BR

//import net.codeinreal.amirahmadadibi.applications.archsample.BR

//BaseObservable class implemetns listener machanisem
//Br class generated by dataBinding contain all the resources used by dataBinding
class Contact( username:String, email:String): BaseObservable() {

    @get:Bindable
    var _username = username
    set(value) {
        field = value
        notifyPropertyChanged(BR._username)
    }


    @get:Bindable
    var _email = email
    set(value) {
        field = value
        notifyPropertyChanged(BR._email)
    }
}