package net.codeinreal.amirahmadadibi.applications.archsample.model
import android.widget.ImageView
import androidx.databinding.BaseObservable
import androidx.databinding.Bindable
import androidx.databinding.BindingAdapter
import com.bumptech.glide.Glide
import com.bumptech.glide.request.RequestOptions
import net.codeinreal.amirahmadadibi.applications.archsample.BR

//import net.codeinreal.amirahmadadibi.applications.archsample.BR

//BaseObservable class implemetns listener machanisem
//Br class generated by dataBinding contain all the resources used by dataBinding
class Contact( username:String, email:String): BaseObservable() {

    @get:Bindable
    var _username = username
    set(value) {
        field = value
        notifyPropertyChanged(BR._username)
    }


    @get:Bindable
    var _email = email
    set(value) {
        field = value
        notifyPropertyChanged(BR._email)
    }

    companion object {
        @JvmStatic
        @BindingAdapter("profileImage")
        fun loadImage(view: ImageView, imageUrl: String) {
            Glide.with(view.context)
                .load(imageUrl)
                .apply(RequestOptions.circleCropTransform())
                .into(view);
        }
    }
}